// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: forge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Complete
	//	*AgentMessage_LogBatch
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_forge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetComplete() *CompleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *AgentMessage) GetLogBatch() *LogBatch {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_LogBatch); ok {
			return x.LogBatch
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Complete struct {
	Complete *CompleteRequest `protobuf:"bytes,4,opt,name=complete,proto3,oneof"`
}

type AgentMessage_LogBatch struct {
	LogBatch *LogBatch `protobuf:"bytes,5,opt,name=log_batch,json=logBatch,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Complete) isAgentMessage_Payload() {}

func (*AgentMessage_LogBatch) isAgentMessage_Payload() {}

type SchedulerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SchedulerMessage_Job
	//	*SchedulerMessage_HeartbeatAck
	Payload       isSchedulerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerMessage) Reset() {
	*x = SchedulerMessage{}
	mi := &file_forge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerMessage) ProtoMessage() {}

func (x *SchedulerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerMessage.ProtoReflect.Descriptor instead.
func (*SchedulerMessage) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulerMessage) GetPayload() isSchedulerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SchedulerMessage) GetJob() *JobSpec {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerMessage_Job); ok {
			return x.Job
		}
	}
	return nil
}

func (x *SchedulerMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

type isSchedulerMessage_Payload interface {
	isSchedulerMessage_Payload()
}

type SchedulerMessage_Job struct {
	Job *JobSpec `protobuf:"bytes,1,opt,name=job,proto3,oneof"`
}

type SchedulerMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

func (*SchedulerMessage_Job) isSchedulerMessage_Payload() {}

func (*SchedulerMessage_HeartbeatAck) isSchedulerMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concurrency   int32                  `protobuf:"varint,1,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_forge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Status        *AgentStatus           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_forge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AgentStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DiskUsageGb       float32                `protobuf:"fixed32,1,opt,name=disk_usage_gb,json=diskUsageGb,proto3" json:"disk_usage_gb,omitempty"`
	DiskFreeGb        float32                `protobuf:"fixed32,2,opt,name=disk_free_gb,json=diskFreeGb,proto3" json:"disk_free_gb,omitempty"`
	DockerImagesCount int32                  `protobuf:"varint,3,opt,name=docker_images_count,json=dockerImagesCount,proto3" json:"docker_images_count,omitempty"`
	ActiveJobsCount   int32                  `protobuf:"varint,4,opt,name=active_jobs_count,json=activeJobsCount,proto3" json:"active_jobs_count,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_forge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{4}
}

func (x *AgentStatus) GetDiskUsageGb() float32 {
	if x != nil {
		return x.DiskUsageGb
	}
	return 0
}

func (x *AgentStatus) GetDiskFreeGb() float32 {
	if x != nil {
		return x.DiskFreeGb
	}
	return 0
}

func (x *AgentStatus) GetDockerImagesCount() int32 {
	if x != nil {
		return x.DockerImagesCount
	}
	return 0
}

func (x *AgentStatus) GetActiveJobsCount() int32 {
	if x != nil {
		return x.ActiveJobsCount
	}
	return 0
}

func (x *AgentStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Stop          bool                   `protobuf:"varint,2,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_forge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatAck) GetStop() bool {
	if x != nil {
		return x.Stop
	}
	return false
}

type CompleteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ExitCode         int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	DurationMs       int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Logs             []*LogEvent            `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	LeaseId          string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	EmittedStepsJson string                 `protobuf:"bytes,6,opt,name=emitted_steps_json,json=emittedStepsJson,proto3" json:"emitted_steps_json,omitempty"`
	Skipped          bool                   `protobuf:"varint,7,opt,name=skipped,proto3" json:"skipped,omitempty"`
	TimedOut         bool                   `protobuf:"varint,8,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_forge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CompleteRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CompleteRequest) GetLogs() []*LogEvent {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *CompleteRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CompleteRequest) GetEmittedStepsJson() string {
	if x != nil {
		return x.EmittedStepsJson
	}
	return ""
}

func (x *CompleteRequest) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

func (x *CompleteRequest) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_forge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{7}
}

func (x *LogEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LogEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Events        []*LogEvent            `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_forge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{8}
}

func (x *LogBatch) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogBatch) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LogBatch) GetEvents() []*LogEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type JobSpec struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	JobId             string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RunId             string                  `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	LeaseId           string                  `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	StepId            string                  `protobuf:"bytes,4,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Image             string                  `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Entrypoint        []string                `protobuf:"bytes,6,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Command           []string                `protobuf:"bytes,7,rep,name=command,proto3" json:"command,omitempty"`
	WorkDir           string                  `protobuf:"bytes,8,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Env               map[string]string       `protobuf:"bytes,9,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inputs            []string                `protobuf:"bytes,10,rep,name=inputs,proto3" json:"inputs,omitempty"`
	TimeoutNs         int64                   `protobuf:"varint,11,opt,name=timeout_ns,json=timeoutNs,proto3" json:"timeout_ns,omitempty"`
	SecretNames       []string                `protobuf:"bytes,12,rep,name=secret_names,json=secretNames,proto3" json:"secret_names,omitempty"`
	DockerSocket      bool                    `protobuf:"varint,13,opt,name=docker_socket,json=dockerSocket,proto3" json:"docker_socket,omitempty"`
	Type              string                  `protobuf:"bytes,14,opt,name=type,proto3" json:"type,omitempty"`
	OrgId             string                  `protobuf:"bytes,15,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId         string                  `protobuf:"bytes,16,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ArtifactUploads   []*ArtifactUploadSpec   `protobuf:"bytes,17,rep,name=artifact_uploads,json=artifactUploads,proto3" json:"artifact_uploads,omitempty"`
	ArtifactDownloads []*ArtifactDownloadSpec `protobuf:"bytes,18,rep,name=artifact_downloads,json=artifactDownloads,proto3" json:"artifact_downloads,omitempty"`
	CommitSha         string                  `protobuf:"bytes,19,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Condition         string                  `protobuf:"bytes,20,opt,name=condition,proto3" json:"condition,omitempty"`
	AlwaysRun         bool                    `protobuf:"varint,21,opt,name=always_run,json=alwaysRun,proto3" json:"always_run,omitempty"`
	PipelineRef       *PipelineRef            `protobuf:"bytes,22,opt,name=pipeline_ref,json=pipelineRef,proto3" json:"pipeline_ref,omitempty"`
	// AppliedStepIDs is a list of step IDs already present in the run hierarchy,
	// used to avoid duplicate step injection by policies.
	AppliedStepIds []string `protobuf:"bytes,24,rep,name=applied_step_ids,json=appliedStepIds,proto3" json:"applied_step_ids,omitempty"`
	// WorkspaceDir is the path to the shared workspace for the run.
	WorkspaceDir string `protobuf:"bytes,25,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	// Ref is the git ref (e.g. "refs/heads/main") the run was submitted for.
	Ref string `protobuf:"bytes,26,opt,name=ref,proto3" json:"ref,omitempty"`
	// TestReport is the workspace-relative path of the test report file this
	// step produces (from the step's `test_report:` config). Empty when unset.
	// Without this field on the wire, agents never saw test_report and test
	// duration recording silently never ran.
	TestReport string `protobuf:"bytes,27,opt,name=test_report,json=testReport,proto3" json:"test_report,omitempty"`
	// PipelineName is the stable pipeline identity used to correlate history
	// (test durations, shard planning) across runs.
	PipelineName  string `protobuf:"bytes,28,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_forge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{9}
}

func (x *JobSpec) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSpec) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobSpec) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *JobSpec) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *JobSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *JobSpec) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *JobSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *JobSpec) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *JobSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *JobSpec) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *JobSpec) GetTimeoutNs() int64 {
	if x != nil {
		return x.TimeoutNs
	}
	return 0
}

func (x *JobSpec) GetSecretNames() []string {
	if x != nil {
		return x.SecretNames
	}
	return nil
}

func (x *JobSpec) GetDockerSocket() bool {
	if x != nil {
		return x.DockerSocket
	}
	return false
}

func (x *JobSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobSpec) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *JobSpec) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *JobSpec) GetArtifactUploads() []*ArtifactUploadSpec {
	if x != nil {
		return x.ArtifactUploads
	}
	return nil
}

func (x *JobSpec) GetArtifactDownloads() []*ArtifactDownloadSpec {
	if x != nil {
		return x.ArtifactDownloads
	}
	return nil
}

func (x *JobSpec) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *JobSpec) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *JobSpec) GetAlwaysRun() bool {
	if x != nil {
		return x.AlwaysRun
	}
	return false
}

func (x *JobSpec) GetPipelineRef() *PipelineRef {
	if x != nil {
		return x.PipelineRef
	}
	return nil
}

func (x *JobSpec) GetAppliedStepIds() []string {
	if x != nil {
		return x.AppliedStepIds
	}
	return nil
}

func (x *JobSpec) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

func (x *JobSpec) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *JobSpec) GetTestReport() string {
	if x != nil {
		return x.TestReport
	}
	return ""
}

func (x *JobSpec) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

type PipelineRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Wait  bool                   `protobuf:"varint,2,opt,name=wait,proto3" json:"wait,omitempty"`
	// Variables are injected into every step of the child pipeline as env vars.
	Variables map[string]string `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ArtifactsSend names artifacts from the PARENT run to make available
	// in the child run.
	ArtifactsSend []string `protobuf:"bytes,4,rep,name=artifacts_send,json=artifactsSend,proto3" json:"artifacts_send,omitempty"`
	// ArtifactsReceive downloads artifacts from the CHILD run into the
	// parent run's artifact store once the child completes.
	ArtifactsReceive []string `protobuf:"bytes,5,rep,name=artifacts_receive,json=artifactsReceive,proto3" json:"artifacts_receive,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PipelineRef) Reset() {
	*x = PipelineRef{}
	mi := &file_forge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRef) ProtoMessage() {}

func (x *PipelineRef) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRef.ProtoReflect.Descriptor instead.
func (*PipelineRef) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{10}
}

func (x *PipelineRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PipelineRef) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

func (x *PipelineRef) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *PipelineRef) GetArtifactsSend() []string {
	if x != nil {
		return x.ArtifactsSend
	}
	return nil
}

func (x *PipelineRef) GetArtifactsReceive() []string {
	if x != nil {
		return x.ArtifactsReceive
	}
	return nil
}

type ArtifactUploadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactUploadSpec) Reset() {
	*x = ArtifactUploadSpec{}
	mi := &file_forge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactUploadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactUploadSpec) ProtoMessage() {}

func (x *ArtifactUploadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactUploadSpec.ProtoReflect.Descriptor instead.
func (*ArtifactUploadSpec) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{11}
}

func (x *ArtifactUploadSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ArtifactUploadSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArtifactDownloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactDownloadSpec) Reset() {
	*x = ArtifactDownloadSpec{}
	mi := &file_forge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactDownloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactDownloadSpec) ProtoMessage() {}

func (x *ArtifactDownloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactDownloadSpec.ProtoReflect.Descriptor instead.
func (*ArtifactDownloadSpec) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactDownloadSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactDownloadSpec) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

var File_forge_proto protoreflect.FileDescriptor

const file_forge_proto_rawDesc = "" +
	"\n" +
	"\vforge.proto\x12\x05forge\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x02\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x124\n" +
	"\bregister\x18\x02 \x01(\v2\x16.forge.RegisterRequestH\x00R\bregister\x127\n" +
	"\theartbeat\x18\x03 \x01(\v2\x17.forge.HeartbeatRequestH\x00R\theartbeat\x124\n" +
	"\bcomplete\x18\x04 \x01(\v2\x16.forge.CompleteRequestH\x00R\bcomplete\x12.\n" +
	"\tlog_batch\x18\x05 \x01(\v2\x0f.forge.LogBatchH\x00R\blogBatchB\t\n" +
	"\apayload\"}\n" +
	"\x10SchedulerMessage\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x0e.forge.JobSpecH\x00R\x03job\x12:\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2\x13.forge.HeartbeatAckH\x00R\fheartbeatAckB\t\n" +
	"\apayload\"\xaa\x01\n" +
	"\x0fRegisterRequest\x12 \n" +
	"\vconcurrency\x18\x01 \x01(\x05R\vconcurrency\x12:\n" +
	"\x06labels\x18\x02 \x03(\v2\".forge.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.forge.AgentStatusR\x06status\"\xc9\x01\n" +
	"\vAgentStatus\x12\"\n" +
	"\rdisk_usage_gb\x18\x01 \x01(\x02R\vdiskUsageGb\x12 \n" +
	"\fdisk_free_gb\x18\x02 \x01(\x02R\n" +
	"diskFreeGb\x12.\n" +
	"\x13docker_images_count\x18\x03 \x01(\x05R\x11dockerImagesCount\x12*\n" +
	"\x11active_jobs_count\x18\x04 \x01(\x05R\x0factiveJobsCount\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"9\n" +
	"\fHeartbeatAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04stop\x18\x02 \x01(\bR\x04stop\"\x8b\x02\n" +
	"\x0fCompleteRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\x04logs\x18\x04 \x03(\v2\x0f.forge.LogEventR\x04logs\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x12,\n" +
	"\x12emitted_steps_json\x18\x06 \x01(\tR\x10emittedStepsJson\x12\x18\n" +
	"\askipped\x18\a \x01(\bR\askipped\x12\x1b\n" +
	"\ttimed_out\x18\b \x01(\bR\btimedOut\"f\n" +
	"\bLogEvent\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"e\n" +
	"\bLogBatch\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12'\n" +
	"\x06events\x18\x03 \x03(\v2\x0f.forge.LogEventR\x06events\"\xce\a\n" +
	"\aJobSpec\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12\x17\n" +
	"\astep_id\x18\x04 \x01(\tR\x06stepId\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x06 \x03(\tR\n" +
	"entrypoint\x12\x18\n" +
	"\acommand\x18\a \x03(\tR\acommand\x12\x19\n" +
	"\bwork_dir\x18\b \x01(\tR\aworkDir\x12)\n" +
	"\x03env\x18\t \x03(\v2\x17.forge.JobSpec.EnvEntryR\x03env\x12\x16\n" +
	"\x06inputs\x18\n" +
	" \x03(\tR\x06inputs\x12\x1d\n" +
	"\n" +
	"timeout_ns\x18\v \x01(\x03R\ttimeoutNs\x12!\n" +
	"\fsecret_names\x18\f \x03(\tR\vsecretNames\x12#\n" +
	"\rdocker_socket\x18\r \x01(\bR\fdockerSocket\x12\x12\n" +
	"\x04type\x18\x0e \x01(\tR\x04type\x12\x15\n" +
	"\x06org_id\x18\x0f \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x10 \x01(\tR\tprojectId\x12D\n" +
	"\x10artifact_uploads\x18\x11 \x03(\v2\x19.forge.ArtifactUploadSpecR\x0fartifactUploads\x12J\n" +
	"\x12artifact_downloads\x18\x12 \x03(\v2\x1b.forge.ArtifactDownloadSpecR\x11artifactDownloads\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x13 \x01(\tR\tcommitSha\x12\x1c\n" +
	"\tcondition\x18\x14 \x01(\tR\tcondition\x12\x1d\n" +
	"\n" +
	"always_run\x18\x15 \x01(\bR\talwaysRun\x125\n" +
	"\fpipeline_ref\x18\x16 \x01(\v2\x12.forge.PipelineRefR\vpipelineRef\x12(\n" +
	"\x10applied_step_ids\x18\x18 \x03(\tR\x0eappliedStepIds\x12#\n" +
	"\rworkspace_dir\x18\x19 \x01(\tR\fworkspaceDir\x12\x10\n" +
	"\x03ref\x18\x1a \x01(\tR\x03ref\x12\x1f\n" +
	"\vtest_report\x18\x1b \x01(\tR\n" +
	"testReport\x12#\n" +
	"\rpipeline_name\x18\x1c \x01(\tR\fpipelineName\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\vPipelineRef\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04wait\x18\x02 \x01(\bR\x04wait\x12?\n" +
	"\tvariables\x18\x03 \x03(\v2!.forge.PipelineRef.VariablesEntryR\tvariables\x12%\n" +
	"\x0eartifacts_send\x18\x04 \x03(\tR\rartifactsSend\x12+\n" +
	"\x11artifacts_receive\x18\x05 \x03(\tR\x10artifactsReceive\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x12ArtifactUploadSpec\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\">\n" +
	"\x14ArtifactDownloadSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest2K\n" +
	"\fAgentService\x12;\n" +
	"\aSession\x12\x13.forge.AgentMessage\x1a\x17.forge.SchedulerMessage(\x010\x01B*Z(github.com/JBraunsmaJr/forge/internal/pbb\x06proto3"

var (
	file_forge_proto_rawDescOnce sync.Once
	file_forge_proto_rawDescData []byte
)

func file_forge_proto_rawDescGZIP() []byte {
	file_forge_proto_rawDescOnce.Do(func() {
		file_forge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forge_proto_rawDesc), len(file_forge_proto_rawDesc)))
	})
	return file_forge_proto_rawDescData
}

var file_forge_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_forge_proto_goTypes = []any{
	(*AgentMessage)(nil),          // 0: forge.AgentMessage
	(*SchedulerMessage)(nil),      // 1: forge.SchedulerMessage
	(*RegisterRequest)(nil),       // 2: forge.RegisterRequest
	(*HeartbeatRequest)(nil),      // 3: forge.HeartbeatRequest
	(*AgentStatus)(nil),           // 4: forge.AgentStatus
	(*HeartbeatAck)(nil),          // 5: forge.HeartbeatAck
	(*CompleteRequest)(nil),       // 6: forge.CompleteRequest
	(*LogEvent)(nil),              // 7: forge.LogEvent
	(*LogBatch)(nil),              // 8: forge.LogBatch
	(*JobSpec)(nil),               // 9: forge.JobSpec
	(*PipelineRef)(nil),           // 10: forge.PipelineRef
	(*ArtifactUploadSpec)(nil),    // 11: forge.ArtifactUploadSpec
	(*ArtifactDownloadSpec)(nil),  // 12: forge.ArtifactDownloadSpec
	nil,                           // 13: forge.RegisterRequest.LabelsEntry
	nil,                           // 14: forge.JobSpec.EnvEntry
	nil,                           // 15: forge.PipelineRef.VariablesEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_forge_proto_depIdxs = []int32{
	2,  // 0: forge.AgentMessage.register:type_name -> forge.RegisterRequest
	3,  // 1: forge.AgentMessage.heartbeat:type_name -> forge.HeartbeatRequest
	6,  // 2: forge.AgentMessage.complete:type_name -> forge.CompleteRequest
	8,  // 3: forge.AgentMessage.log_batch:type_name -> forge.LogBatch
	9,  // 4: forge.SchedulerMessage.job:type_name -> forge.JobSpec
	5,  // 5: forge.SchedulerMessage.heartbeat_ack:type_name -> forge.HeartbeatAck
	13, // 6: forge.RegisterRequest.labels:type_name -> forge.RegisterRequest.LabelsEntry
	4,  // 7: forge.HeartbeatRequest.status:type_name -> forge.AgentStatus
	7,  // 8: forge.CompleteRequest.logs:type_name -> forge.LogEvent
	16, // 9: forge.LogEvent.ts:type_name -> google.protobuf.Timestamp
	7,  // 10: forge.LogBatch.events:type_name -> forge.LogEvent
	14, // 11: forge.JobSpec.env:type_name -> forge.JobSpec.EnvEntry
	11, // 12: forge.JobSpec.artifact_uploads:type_name -> forge.ArtifactUploadSpec
	12, // 13: forge.JobSpec.artifact_downloads:type_name -> forge.ArtifactDownloadSpec
	10, // 14: forge.JobSpec.pipeline_ref:type_name -> forge.PipelineRef
	15, // 15: forge.PipelineRef.variables:type_name -> forge.PipelineRef.VariablesEntry
	0,  // 16: forge.AgentService.Session:input_type -> forge.AgentMessage
	1,  // 17: forge.AgentService.Session:output_type -> forge.SchedulerMessage
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_forge_proto_init() }
func file_forge_proto_init() {
	if File_forge_proto != nil {
		return
	}
	file_forge_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Complete)(nil),
		(*AgentMessage_LogBatch)(nil),
	}
	file_forge_proto_msgTypes[1].OneofWrappers = []any{
		(*SchedulerMessage_Job)(nil),
		(*SchedulerMessage_HeartbeatAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forge_proto_rawDesc), len(file_forge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forge_proto_goTypes,
		DependencyIndexes: file_forge_proto_depIdxs,
		MessageInfos:      file_forge_proto_msgTypes,
	}.Build()
	File_forge_proto = out.File
	file_forge_proto_goTypes = nil
	file_forge_proto_depIdxs = nil
}
